### ISSUE TITLE
Document is still blurred

### ISSUE THREAD

**Issue by Filtar2000** [lambwheit/Studocu-Paywall-Bypass#3]

**Comment by lambwheit** [comment]
send the document link

**Comment by Filtar2000** [comment]
https://www.studocu.com/it/document/libera-universita-internazionale-degli-studi-sociali-guido-carli/oil-gas-industry-fundamentals-challenged-by-new-sources-and-new-geopolitics/geopolitical-scenarios-book/29131967

**Comment by lambwheit** [comment]
oh it's a new update, idk if it's even bypassable

**Comment by Filtar2000** [comment]
ok let me know if you have news. Thank you!

**Comment by lambwheit** [comment]
yea i think this project might need to be archived now, the html no longer has the part of the document that is unblured it is just replaced with a blured pic
![image](https://github.com/lambwheit/Studocu-Paywall-Bypass/assets/38606611/155d4749-80d8-44df-ad03-23e79949c0da)
